services:
  app:
   image: aruntanakam/restapp:seventh-image
   
   ports:
     - "4000:4000"
     
   environment:
     - DB_HOST=db
     - LOGICAL_DATABASE=restappdb
     - DB_USERNAME=restuser
     - DB_PASSWORD=restuser@123
     
   depends_on:
     db:
      condition: service_healthy
     
   networks:
      - rest_app_network
      
   volumes:
      - app-logs:/app/logs
      
  db:
   image: mysql:latest
   
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=restappdb
     - MYSQL_USER=restuser
     - MYSQL_PASSWORD=restuser@123
     
   networks:
     - rest_app_network
     
   healthcheck:
     test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
     interval: 10s
     timeout: 5s
     retries: 3 
     
   volumes:
       - db-volume:/var/lib/mysql
    
     
networks:
  rest_app_network:
    driver: bridge
    
volumes:
  db-volume:
  app-logs:
  